import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TopMenu } from "@/components/ui/top-menu/TopMemu";
import TopNavbar from '@/components/ui/top-navbar/TopNavbar';
import AgregarFotosEmpren from "./emprendedores/configuracionEmprendedor/AgregarFotosEmpren";
import TipoPublicacion from "./emprendedores/registroProductos/TipoPublicacion";
import TipoMascota from "./emprendedores/registroProductos/TipoMascota";
import FormularioProductos from "./emprendedores/registroProductos/FormularioProducto";
import ArchivosMultimedia from "./emprendedores/registroProductos/ArchivosMultimedia";
import ListaProductos from "./emprendedores/lista-productos/ListaProductos";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <TopNavbar/>
        <TopMenu/>
        <ListaProductos/>
        {children}
      </body>
    </html>
  );
}
