import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TopMenu } from "@/components/ui/top-menu/TopMemu";
import TopNavbar from '@/components/ui/top-navbar/TopNavbar';
import TipoPublicacion from "./(emprendedor)/emprendedores/components/registro-productos/TipoPublicacion";
import TipoMascota from "./(emprendedor)/emprendedores/components/registro-productos/TipoMascota";
import FormularioProductos from "./(emprendedor)/emprendedores/components/registro-productos/FormularioProducto";
import ArchivosMultimedia from "./(emprendedor)/emprendedores/components/registro-productos/ArchivosMultimedia";
import ListaProductos from "./(emprendedor)/emprendedores/components/lista-productos/ListaProductos";
import ListaPedidos from "./(emprendedor)/emprendedores/components/lista-pedidos/ListaPedidos";
import OfertaProducto from "./(emprendedor)/emprendedores/components/oferta-producto/OfertaProducto";
import ComponentePadre from "./(emprendedor)/emprendedores/components/oferta-producto/OfertaProducto";





const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <TopNavbar/>
        <TopMenu/>
        {children}
      </body>
    </html>
  );
}
