import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TopMenu } from "@/components/ui/top-menu/TopMemu";
import TopNavbar from '@/components/ui/top-navbar/TopNavbar';
import CheckHorarios from "./emprendedores/CheckHorarios";
import AgregarFotosEmpren from "./emprendedores/AgregarFotosEmpren";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <TopNavbar/>
        <AgregarFotosEmpren/>
        {children}
      </body>
    </html>
  );
}
